Configura projeto
kleytonmr/blog pull request #5
Opened 2018-03-11 21:58 UTC by kleytonmr

2018-03-12 09:29 UTC, possatto requested changes

2018-03-12 09:29 UTC, possatto commented on config/database.yml
> +  password: pguser
no ambiente de desenvolvimento é melhor usar assim:
```ruby
username: admin
password: 
```

2018-03-12 09:29 UTC, possatto commented on Gemfile
> +gem 'pg', '~> 0.18'
usar a versão mais nova `gem 'pg', '~> 1.0'`

2018-03-13 10:54 UTC, kleytonmr commented on Gemfile
> +gem 'pg', '~> 0.18'
Eu deixei  nessa versão porque é a  versão suportada pelo heroku.

2018-03-13 13:31 UTC, possatto commented on config/database.yml
> +  password: pguser
@kleytonmr falei errado. O usuário deve ser `root` e sem senha. Foi mal

2018-03-13 13:31 UTC, possatto commented on Gemfile
> +gem 'pg', '~> 0.18'
@kleytonmr onde vc viu isso?? Na documentação deles não especifica a versão.
![image](https://user-images.githubusercontent.com/1759408/37344584-81d49712-26a9-11e8-8af6-c2b8379328ea.png)

https://devcenter.heroku.com/articles/getting-started-with-rails5#database

2018-03-13 14:05 UTC, kleytonmr commented on Gemfile
> +gem 'pg', '~> 0.18'
Falei besteira então! Sorry! Eu vi isso quando dei deploy, ele disse que não era suportada versões superiores a esta.

2018-03-20 14:00 UTC, possatto commented
@kleytonmr corrige esse PR primeiro ;)

2018-03-21 11:28 UTC, merged